-- Auto-generated from proofofplay/piratenation-art Combat Cards (CC0)
local Cards = {}

Cards.List = {
	{ id = "wheretheygo_06", name = "WhereTheyGo 06", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "ap01", name = "AP01", kind = "Resource", ap = 0, damage = 0, shield = 0, heal = 0, draw = 0 },
	{ id = "ap02", name = "AP02", kind = "Resource", ap = 0, damage = 0, shield = 0, heal = 0, draw = 0 },
	{ id = "ap03", name = "AP03", kind = "Resource", ap = 0, damage = 0, shield = 0, heal = 0, draw = 0 },
	{ id = "ap04", name = "AP04", kind = "Resource", ap = 0, damage = 0, shield = 0, heal = 0, draw = 0 },
	{ id = "abyssal_tentacles", name = "Abyssal Tentacles", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "ace_in_the_hole", name = "Ace In The Hole", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "act_with_haste", name = "Act with Haste", kind = "Skill", ap = 0, damage = 0, shield = 1, heal = 0, draw = 1 },
	{ id = "advenced_attack_plan", name = "Advenced Attack Plan", kind = "Skill", ap = 0, damage = 0, shield = 1, heal = 0, draw = 1 },
	{ id = "amplify_affinity", name = "Amplify Affinity", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "another_round", name = "Another Round", kind = "Skill", ap = 0, damage = 0, shield = 1, heal = 0, draw = 1 },
	{ id = "barbed_shield", name = "Barbed Shield", kind = "Defend", ap = 1, damage = 0, shield = 5, heal = 0, draw = 0 },
	{ id = "barnacle_barrier", name = "Barnacle Barrier", kind = "Defend", ap = 1, damage = 0, shield = 5, heal = 0, draw = 0 },
	{ id = "basic_attack_plan", name = "Basic Attack Plan", kind = "Skill", ap = 0, damage = 0, shield = 1, heal = 0, draw = 1 },
	{ id = "basic_relief", name = "Basic Relief", kind = "Defend", ap = 1, damage = 0, shield = 2, heal = 4, draw = 0 },
	{ id = "big_guns", name = "Big Guns", kind = "Attack", ap = 2, damage = 7, shield = 0, heal = 0, draw = 0 },
	{ id = "blinding_glare", name = "Blinding Glare", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "bombardment", name = "Bombardment", kind = "Attack", ap = 2, damage = 7, shield = 0, heal = 0, draw = 0 },
	{ id = "breach_the_hull", name = "Breach the Hull", kind = "Attack", ap = 2, damage = 7, shield = 0, heal = 0, draw = 0 },
	{ id = "briny_relief", name = "Briny Relief", kind = "Defend", ap = 1, damage = 0, shield = 2, heal = 4, draw = 0 },
	{ id = "broadside", name = "Broadside", kind = "Attack", ap = 2, damage = 7, shield = 0, heal = 0, draw = 0 },
	{ id = "cannon_blast", name = "Cannon Blast", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "cant_hurt_me", name = "Cant Hurt Me", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "careful_aim", name = "Careful Aim", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "careful_planning", name = "Careful Planning", kind = "Skill", ap = 0, damage = 0, shield = 1, heal = 0, draw = 1 },
	{ id = "carronade", name = "Carronade", kind = "Attack", ap = 2, damage = 7, shield = 0, heal = 0, draw = 0 },
	{ id = "clean_shot", name = "Clean Shot", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "close_inspection", name = "Close Inspection", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "coiled_strike", name = "Coiled Strike", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "commanding_presence", name = "Commanding Presence", kind = "Skill", ap = 0, damage = 0, shield = 1, heal = 0, draw = 1 },
	{ id = "commanding_stance", name = "Commanding Stance", kind = "Skill", ap = 0, damage = 0, shield = 1, heal = 0, draw = 1 },
	{ id = "continuous_repairs", name = "Continuous Repairs", kind = "Defend", ap = 1, damage = 0, shield = 2, heal = 4, draw = 0 },
	{ id = "counter_attack", name = "Counter Attack", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "crippling_shot", name = "Crippling Shot", kind = "Attack", ap = 1, damage = 6, shield = 0, heal = 0, draw = 0 },
	{ id = "critical_target", name = "Critical Target", kind = "Attack", ap = 1, damage = 6, shield = 0, heal = 0, draw = 0 },
	{ id = "cross_counter", name = "Cross Counter", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "deadeye", name = "DeadEye", kind = "Attack", ap = 1, damage = 6, shield = 0, heal = 0, draw = 0 },
	{ id = "defensive_strike", name = "Defensive Strike", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "dejavu", name = "DejaVu", kind = "Skill", ap = 0, damage = 0, shield = 1, heal = 0, draw = 1 },
	{ id = "distress_call", name = "Distress Call", kind = "Skill", ap = 0, damage = 0, shield = 1, heal = 0, draw = 1 },
	{ id = "do_it_again", name = "Do It Again", kind = "Skill", ap = 0, damage = 0, shield = 1, heal = 0, draw = 1 },
	{ id = "double_barrel", name = "Double Barrel", kind = "Attack", ap = 2, damage = 7, shield = 0, heal = 0, draw = 0 },
	{ id = "double_shot", name = "Double Shot", kind = "Attack", ap = 2, damage = 7, shield = 0, heal = 0, draw = 0 },
	{ id = "double_strike", name = "Double Strike", kind = "Attack", ap = 2, damage = 7, shield = 0, heal = 0, draw = 0 },
	{ id = "evasive_maneuvers", name = "Evasive Maneuvers", kind = "Defend", ap = 1, damage = 0, shield = 5, heal = 0, draw = 0 },
	{ id = "expose_weakness", name = "Expose Weakness", kind = "Attack", ap = 1, damage = 6, shield = 0, heal = 0, draw = 0 },
	{ id = "extra_power", name = "Extra Power", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "fast_hands", name = "Fast Hands", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "find_inspired_attack", name = "Find Inspired Attack", kind = "Skill", ap = 0, damage = 0, shield = 1, heal = 0, draw = 1 },
	{ id = "find_the_weak_points", name = "Find the Weak Points", kind = "Attack", ap = 1, damage = 6, shield = 0, heal = 0, draw = 0 },
	{ id = "fix_it", name = "Fix It!", kind = "Defend", ap = 1, damage = 0, shield = 2, heal = 4, draw = 0 },
	{ id = "fleetfoot", name = "Fleetfoot", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "focus_target", name = "Focus Target", kind = "Skill", ap = 0, damage = 0, shield = 1, heal = 0, draw = 1 },
	{ id = "fortitude", name = "Fortitude", kind = "Defend", ap = 1, damage = 0, shield = 5, heal = 0, draw = 0 },
	{ id = "ghost_mode", name = "Ghost Mode", kind = "Skill", ap = 0, damage = 0, shield = 1, heal = 0, draw = 1 },
	{ id = "great_relief", name = "Great Relief", kind = "Defend", ap = 1, damage = 0, shield = 2, heal = 4, draw = 0 },
	{ id = "gut_punch", name = "Gut Punch", kind = "Attack", ap = 1, damage = 6, shield = 0, heal = 0, draw = 0 },
	{ id = "hardened_shield", name = "Hardened Shield", kind = "Defend", ap = 1, damage = 0, shield = 5, heal = 0, draw = 0 },
	{ id = "harpoon_the_hull", name = "Harpoon The Hull", kind = "Attack", ap = 2, damage = 7, shield = 0, heal = 0, draw = 0 },
	{ id = "hasty_plan", name = "Hasty Plan", kind = "Skill", ap = 0, damage = 0, shield = 1, heal = 0, draw = 1 },
	{ id = "heavy_blow", name = "Heavy Blow", kind = "Attack", ap = 2, damage = 7, shield = 0, heal = 0, draw = 0 },
	{ id = "helm_splitter", name = "Helm Splitter", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "hit_em_where_it_hurts", name = "Hit Em Where it Hurts", kind = "Attack", ap = 1, damage = 6, shield = 0, heal = 0, draw = 0 },
	{ id = "hit_and_run", name = "Hit and Run", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "hit_the_weak_spot", name = "Hit the Weak Spot", kind = "Attack", ap = 1, damage = 6, shield = 0, heal = 0, draw = 0 },
	{ id = "hit_the_dry_powder", name = "Hit the Dry Powder", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "hit_the_weakest_point", name = "Hit the Weakest Point", kind = "Attack", ap = 1, damage = 6, shield = 0, heal = 0, draw = 0 },
	{ id = "hull_piercer", name = "Hull Piercer", kind = "Attack", ap = 2, damage = 7, shield = 0, heal = 0, draw = 0 },
	{ id = "i_dare_you", name = "I Dare You", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "immediate_repairs", name = "Immediate Repairs", kind = "Defend", ap = 1, damage = 0, shield = 2, heal = 4, draw = 0 },
	{ id = "imposing_order", name = "Imposing Order", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "improvised_plan", name = "Improvised Plan", kind = "Skill", ap = 0, damage = 0, shield = 1, heal = 0, draw = 1 },
	{ id = "inspiration", name = "Inspiration", kind = "Skill", ap = 0, damage = 0, shield = 1, heal = 0, draw = 1 },
	{ id = "inspired_attack", name = "Inspired Attack", kind = "Skill", ap = 0, damage = 0, shield = 1, heal = 0, draw = 1 },
	{ id = "iron_fangs", name = "Iron Fangs", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "iron_guard", name = "Iron Guard", kind = "Defend", ap = 1, damage = 0, shield = 5, heal = 0, draw = 0 },
	{ id = "iron_tides", name = "Iron Tides", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "iron_volley", name = "Iron Volley", kind = "Attack", ap = 2, damage = 7, shield = 0, heal = 0, draw = 0 },
	{ id = "jolly_rigging", name = "Jolly Rigging", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "last_ditch", name = "Last Ditch", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "leeching_chomp", name = "Leeching Chomp", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "leeching_rain", name = "Leeching Rain", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "light_cover", name = "Light Cover", kind = "Defend", ap = 1, damage = 0, shield = 5, heal = 0, draw = 0 },
	{ id = "long_9s", name = "Long 9s", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "making_holes", name = "Making Holes", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "mariner_s_mend", name = "Mariner s Mend", kind = "Defend", ap = 1, damage = 0, shield = 2, heal = 4, draw = 0 },
	{ id = "masterful_plan", name = "Masterful Plan", kind = "Skill", ap = 0, damage = 0, shield = 1, heal = 0, draw = 1 },
	{ id = "menacing_blow", name = "Menacing Blow", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "mending_tides", name = "Mending Tides", kind = "Defend", ap = 1, damage = 0, shield = 2, heal = 4, draw = 0 },
	{ id = "misdirection", name = "Misdirection", kind = "Skill", ap = 0, damage = 0, shield = 1, heal = 0, draw = 1 },
	{ id = "musket_shot", name = "Musket Shot", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "new_plan", name = "New Plan", kind = "Skill", ap = 0, damage = 0, shield = 1, heal = 0, draw = 1 },
	{ id = "overwatch", name = "Overwatch", kind = "Skill", ap = 0, damage = 0, shield = 1, heal = 0, draw = 1 },
	{ id = "paralyzing_strike", name = "Paralyzing Strike", kind = "Attack", ap = 1, damage = 6, shield = 0, heal = 0, draw = 0 },
	{ id = "patch_work", name = "Patch Work", kind = "Defend", ap = 1, damage = 0, shield = 2, heal = 4, draw = 0 },
	{ id = "phoenix_armor", name = "Phoenix Armor", kind = "Defend", ap = 1, damage = 0, shield = 2, heal = 4, draw = 0 },
	{ id = "player2advantage", name = "Player2Advantage", kind = "Skill", ap = 0, damage = 0, shield = 1, heal = 0, draw = 1 },
	{ id = "poseidon_s_blessing", name = "Poseidon s Blessing", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "poseidons_shield", name = "Poseidons Shield", kind = "Defend", ap = 1, damage = 0, shield = 5, heal = 0, draw = 0 },
	{ id = "power_shot", name = "Power Shot", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "quick_draw", name = "Quick Draw", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "quick_fix", name = "Quick Fix", kind = "Defend", ap = 1, damage = 0, shield = 2, heal = 4, draw = 0 },
	{ id = "quick_thinking", name = "Quick Thinking", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "rain_of_iron", name = "Rain of Iron", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "rapid_strike", name = "Rapid Strike", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "rapid_fire", name = "Rapid Fire", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "reactive_armor", name = "Reactive Armor", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "refill_cannon", name = "Refill Cannon", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "regroup", name = "Regroup", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "relief", name = "Relief", kind = "Defend", ap = 1, damage = 0, shield = 2, heal = 4, draw = 0 },
	{ id = "reload", name = "Reload", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "remember_that", name = "Remember That", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "renew", name = "Renew", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "respond_in_kind", name = "Respond in Kind", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "retaliate", name = "Retaliate", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "riposte_stance", name = "Riposte Stance", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "roll_with_the_blow", name = "Roll with the Blow", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "rope_a_dope", name = "Rope A Dope", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "rummage", name = "Rummage", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "scatter_shot", name = "Scatter Shot", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "scrape_the_bottom", name = "Scrape The Bottom", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "search_and_rescue", name = "Search and Rescue", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "sharp_wit", name = "Sharp Wit", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "shellsplitter", name = "ShellSplitter", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "shell_of_defense", name = "Shell of Defense", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "shielded_strike", name = "Shielded Strike", kind = "Defend", ap = 1, damage = 0, shield = 5, heal = 0, draw = 0 },
	{ id = "slippery_like_an_eel", name = "Slippery like an Eel", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "slow_drip", name = "Slow Drip", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "sneaky", name = "Sneaky", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "sober_up", name = "Sober Up", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "stack_the_deck", name = "Stack The Deck", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "steady_aim", name = "Steady Aim", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "stick_and_move", name = "Stick and Move", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "sticky_fingers", name = "Sticky Fingers", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "storm_of_iron", name = "Storm of Iron", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "supply_run", name = "Supply Run", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "swift_course", name = "Swift Course", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "swift_winds", name = "Swift Winds", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "tail_sweep", name = "Tail Sweep", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "that_s_a_big_hole", name = "That s a Big Hole", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "the_power_of_rum", name = "The Power of Rum", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "thorny_guard", name = "Thorny Guard", kind = "Defend", ap = 1, damage = 0, shield = 5, heal = 0, draw = 0 },
	{ id = "thoughtful_planning", name = "Thoughtful Planning", kind = "Skill", ap = 0, damage = 0, shield = 1, heal = 0, draw = 1 },
	{ id = "thrilling_shot", name = "Thrilling Shot", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "thunder_struck", name = "Thunder Struck", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "time_rewritten", name = "Time Rewritten", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "total_relief", name = "Total Relief", kind = "Defend", ap = 1, damage = 0, shield = 2, heal = 4, draw = 0 },
	{ id = "twin_barrel_shot", name = "Twin Barrel Shot", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "use_the_good_stuff", name = "Use the Good Stuff", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "vampiric_rain", name = "Vampiric Rain", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
	{ id = "vampiric_strike", name = "Vampiric Strike", kind = "Attack", ap = 1, damage = 4, shield = 0, heal = 0, draw = 0 },
}

Cards.ById = {}
for _, c in ipairs(Cards.List) do
	Cards.ById[c.id] = c
end

Cards.StarterDeckIds = {
	"cannon_blast",
	"basic_attack_plan",
	"basic_relief",
	"broadside",
	"musket_shot",
	"patch_work",
	"careful_aim",
	"evasive_maneuvers",
	"wheretheygo_06",
	"abyssal_tentacles",
	"ace_in_the_hole",
	"amplify_affinity",
}

function Cards.CloneStarterDeck()
	local d = table.create(#Cards.StarterDeckIds)
	for i, id in ipairs(Cards.StarterDeckIds) do
		d[i] = id
	end
	return d
end

function Cards.Get(id)
	return Cards.ById[id]
end

return Cards
